server:
  port: 8080



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3777/shop
    username: root
    password: rnrdj123


  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
   # show-sql: true




#  cloud:
#    aws:
#      credentials:
#        access-key: ${AWS_ACCESS_KEY_ID}
#        secret-key: ${AWS_SECRET_ACCESS_KEY}
#      s3:
#        bucket: ${AWS_BUCKET}
#      region:
#        static: ap-northeast-2
#      stack:
#        auto: false



#PSP:
#  toss:
#    secretKey: ${TOSS_SECRET_KEY}
#    url: https://api.tosspayments.com



com:
  test:
    upload:
      path: C:\\dev

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.cache: trace
