server:
  port: 9090



spring:


  #같은 네트워크 내에서는 컨테이너의 내부 포트를 사용해야 하므로, 3306
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3377/shop?allowPublicKeyRetrieval=true
    username: root
    password:


  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
   # show-sql: true




  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${AWS_BUCKET}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false



PSP:
  toss:
    secretKey: ${TOSS_SECRET_KEY}
    url: https://api.tosspayments.com



com:
  test:
    upload:
      path: C:\\dev

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.cache: trace


endpoints:
  sun-shop-product-service:
    url: http://127.0.0.1:9090